#!/usr/bin/env python3

from sys import argv
import os
import datetime

from constants import URGENT, NORMAL
from task_manager import TaskManager

def clear ():
    print("\033[2J")
    print("\033[H")

if __name__ == "__main__":
    tm = TaskManager.load()
    if len(argv) < 2:
        clear()
        print(f"{tm}")
    else:
        match argv[1]:
            case "-at" :
                task = argv[2]
                y,m,d = datetime.datetime.today().year, int(argv[3]), int(argv[4])
                date = datetime.datetime(y,m,d)
                urgent = input("is it urgent [y/n] : ")
                tag = URGENT if urgent == "y" else NORMAL
                tm.add_task(task, date, tag)
            case "-ap" :
                project_name = argv[2]
                tm.add_project(project_name)
            case "-apt" :
                project_name = argv[2]
                task = argv[3]
                y,m,d = datetime.datetime.today().year, int(argv[4]), int(argv[5])
                date = datetime.datetime(y,m,d)
                urgent = input("is it urgent [y/n] : ")
                tag = URGENT if urgent == "y" else NORMAL
                tm.add_project_task(project_name,task, date, tag)
            case "-ct" :
                tm.complete_task (int(argv[2]))
            case "-cpt" :
                tm.complete_project_task (argv[2],int(argv[3]))
            case "-apm" :
                tm.add_project_milestone (argv[2], argv[3])
            case "-h" :
                display_help()
            case _ :
                clear()
                print(f"{tm}")

    tm.save()
